In [1]:
import numpy as np
arr1=np.zeros((3,3))
arr2=np.ones((1,3))
arr3=np.random.randint(0,1000,(4,4))
arr1,arr2,arr3

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.]]),
 array([[654,   8, 750, 988],
        [965, 275, 572, 627],
        [689, 648, 197, 834],
        [696, 320, 600, 766]]))

In [3]:
import numpy as np
arr=np.random.randint(0,100,(3,3))
print(arr)
he=np.sum(arr)
ji=np.prod(arr)
jun=np.mean(arr)
Max=np.max(arr)
Min=np.min(arr)
arr[1,1]=0
he,ji,jun,Max,Min,arr,arr.std(),arr.var()



[[32 91 80]
 [42 70 46]
 [85 76 93]]


(615,
 -1680654336,
 68.33333333333333,
 93,
 32,
 array([[32, 91, 80],
        [42,  0, 46],
        [85, 76, 93]]),
 30.24386479973569,
 914.6913580246915)

In [34]:
import numpy as np
arr1=np.random.randint(0,20,(1,9))
arr2=np.random.randint(0,20,(1,9))
arrA=arr1.reshape(3,3)
arrB=arr2.reshape(3,3)
arrC=np.vstack((arrA,arrB))
arrD=np.hstack((arrA,arrB))
arrA,arrB,arrC,arrD



(array([[19,  0,  5],
        [16,  2,  4],
        [12,  4,  5]]),
 array([[19,  7,  9],
        [ 4,  5, 16],
        [18, 12, 13]]),
 array([[19,  0,  5],
        [16,  2,  4],
        [12,  4,  5],
        [19,  7,  9],
        [ 4,  5, 16],
        [18, 12, 13]]),
 array([[19,  0,  5, 19,  7,  9],
        [16,  2,  4,  4,  5, 16],
        [12,  4,  5, 18, 12, 13]]))

In [45]:
import numpy as np
A=np.mat("1 -2 1;0 2 -8;-4 5 9")
P,Q= np.linalg.eig(A)

U, Sigma, V = np.linalg.svd(A)

b=np.array([0,8,-9])
X=np.linalg.solve(A,b)
P,Q,U,Sigma,V,X


(array([0.02752148+0.j        , 5.98623926+6.06922064j,
        5.98623926-6.06922064j]),
 matrix([[-0.86832079+0.j        ,  0.1988291 -0.13261668j,
           0.1988291 +0.13261668j],
         [-0.48158091+0.j        , -0.71901045+0.j        ,
          -0.71901045-0.j        ],
         [-0.1187385 +0.j        ,  0.35826846+0.54547913j,
           0.35826846-0.54547913j]]),
 matrix([[ 0.0154013 ,  0.42284401,  0.9060716 ],
         [-0.54920827, -0.75366444,  0.36105427],
         [ 0.83554358, -0.50318272,  0.22062201]]),
 array([12.753856  ,  5.77394316,  0.02715914]),
 matrix([[-0.26084449,  0.23902565,  0.93532181],
         [ 0.42182177, -0.84325917,  0.33313716],
         [ 0.86834702,  0.48143609,  0.11913328]]),
 array([29., 16.,  3.]))

In [40]:
import numpy as np

A = np.mat("1 -2 1;0 2 -8;-4 5 9")
print ("A\n", A)
b = np.array([0, 8, -9])
print ("b\n", b)
x = np.linalg.solve(A, b)
print ("Solution", x)




A
 [[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
b
 [ 0  8 -9]
Solution [29. 16.  3.]
